services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analyzer-container
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src:ro  # Mount source code as read-only for debugging
    env_file:
      - .env
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/text-analyzer
      NODE_ENV: development
      FRONTEND_URL: http://localhost:8080
      API_URL: http://localhost:5000
      THROTTLE_TTL: 60000
      THROTTLE_LIMIT: 10
      MONGODB_TEST_URI: mongodb://mongodb:27017/text-test
      TEST_JWT_SECRET: test-secret
      TEST_THROTTLE_TTL: 60000
      TEST_THROTTLE_LIMIT: 100
    depends_on:
      - mongodb
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app-network:
    driver: bridge
